site_name: Pelintekoa Phaserilla
nav:
- Etusivu: index.md
- Kurssi:
  - Perustukset: kurssi/perustukset.md
  - "Hello World": kurssi/helloworld.md
  - "Suunnittelupalaveri": kurssi/suunnittelupalaveri.md
  - "Javascript, osa 1": kurssi/javascript.md
theme:
  name: 'material'
  language: 'fi'