site_name: Pelintekoa Phaserilla
nav:
- Etusivu: index.md
- Kurssi:
  - Perustukset: kurssi/perustukset.md
  - "Hello World": kurssi/helloworld.md
  - "Suunnittelupalaveri": kurssi/suunnittelupalaveri.md
  - "Phaserin perusasetukset": kurssi/phaser-perusasetukset.md
  - "Alussa on sana": kurssi/sana-spriteksi.md
  - "Syötteiden lukemista": kurssi/syote.md
  - "Reagoidaan äänellä": kurssi/aanta-ja-vimmaa.md
theme:
  name: 'material'
  language: 'fi'